#SPDX-License-Identifier: MIT-0
---
# tasks file for cert-manager

# Config Ansible Controler config

- name: Install Python pip3 if necessary on Anisble controler
  ansible.builtin.package:
    name: python3-pip
    state: present
  delegate_to: localhost
  become: true

- name: Install Python Venv on Ansible controler
  ansible.builtin.package:
    name: python3-venv
    state: present
  delegate_to: localhost

- name: Create Python Virtual Environment and Install Kubernetes SDK ( Ubuntu >= 24.04 )
  ansible.builtin.pip:
    name:
      - kubernetes
      - PyYAML
    virtualenv: "{{ PYTHON_VENV_PATH }}"
    virtualenv_command: python3 -m venv
    state: present

