apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.POSTGRES_PASSWORD | quote }}
  POSTGRES_DB: {{ .Values.POSTGRES_DB | quote }}
  SECRET_KEY: {{ .Values.SECRET_KEY | quote }}
  FIRST_SUPERUSER_PASSWORD: {{ .Values.FIRST_SUPERUSER_PASSWORD | quote }}