all:
  children:

    k8s.masters:
      hosts:
        master_01:
          ansible_host: 10.10.10.104
        master_02:
          ansible_host: 10.10.10.100
        master_03:
          ansible_host: 10.10.10.105

    k8s.workers:
      hosts:
        worker_01:
          ansible_host: 10.10.10.103
        worker_02:
          ansible_host: 10.10.10.106
