all:
  children:

    k8s.master:
      hosts:
        kubernetes:
          ansible_host: ####
          http_port: ####

    k8s.nodes:
      hosts:
        kubernetes:
          ansible_host: ####
          http_port: ####