- name: Kubernetes masters config
  hosts: k8s.masters
  become: true
  roles:
    - k8s
    - k8s-master
    - helm
#    - metallb
#    - cert-manager
#    - traefik

- name: Kubernetes workers config
  hosts: k8s.workers
  become: true
  roles:
    - k8s
    - k8s-worker
