- name: Kubernetes global config
  hosts: k8s_global
  become: true
  roles:
    - k8s

- name: Kubernetes masters config
  hosts: k8s_masters
  become: true
  roles:
    - k8s-master
    - helm

- name: Kubernetes workers config
  hosts: k8s_workers
  become: true
  roles:
    - k8s-worker

- name: Cluster add-ons
  hosts: k8s_masters
  become: true
  roles:
    - metallb
#    - cert-manager
#    - traefik
