# roles/traefik/defaults/main.yml
#SPDX-License-Identifier: MIT-0
---
# safe-to-override defaults for traefik

TRAEFIK_VERSION: "v3.3.2"
TRAEFIK_CHART_VERSION: "33.2.1"
TRAEFIK_REPLICAS: 2
LETSENCRYPT_ISSUER: letsencrypt-staging   # switch to letsencrypt-prod once validated

TRAEFIK_CPU_REQUEST: "100m"
TRAEFIK_MEMORY_REQUEST: "128Mi"
TRAEFIK_CPU_LIMIT: "500m"
TRAEFIK_MEMORY_LIMIT: "512Mi"
