# roles/traefik/defaults/main.yml
#SPDX-License-Identifier: MIT-0
---
# safe-to-override defaults for traefik

traefik_version: "v3.3.2"
traefik_chart_version: "33.2.1"
traefik_replicas: 2
letsencrypt_issuer: letsencrypt-staging   # switch to letsencrypt-prod once validated

traefik_cpu_request: "100m"
traefik_memory_request: "128Mi"
traefik_cpu_limit: "500m"
traefik_memory_limit: "512Mi"