# roles/traefik/vars/main.yml
#SPDX-License-Identifier: MIT-0
---
# vars file for traefik

KUBECONFIG_PATH: /etc/kubernetes/admin.conf

TRAEFIK_LOG_LEVEL: INFO
TRAEFIK_NAMESPACE: traefik

VAULT_DASHBOARD_USER:
VAULT_DASHBOARD_PASSWORD:
TERRAFORM_APP_DOMAIN:
