#SPDX-License-Identifier: MIT-0
---
# tasks file for k8s-master

- name: Check if Kubernetes is already initialized
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_init_check

- name: Initialize the Kubernetes cluster using kubeadm
  ansible.builtin.command: kubeadm init --apiserver-advertise-address="{{ node_ip }}" --apiserver-cert-extra-sans="{{ node_ip }}" --node-name "{{ ansible_hostname }}" --pod-network-cidr=192.168.0.0/16
  when: not k8s_init_check.stat.exists  

### Setup the kube config file for user to access the Kubernetes cluster.

- name: Setup kubeconfig for user
  ansible.builtin.command: "{{ item }}"
  with_items:
    - mkdir -p /home/"{{ USER }}"/.kube
    - cp -i /etc/kubernetes/admin.conf /home/"{{ USER }}"/.kube/config
    - chown "{{ USER }}":"{{ USER }}" /home/"{{ USER }}"/.kube/config

### Setup the container networking provider and the network policy engine.

- name: Install calico pod network
  ansible.builtin.command: kubectl apply -f "{{ CALICO_REPO }}"
  become: false

### Generate kube join command.

- name: Generate join command
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  ansible.builtin.copy:
    content: "{{ join_command.stdout_lines[0] }}"
    dest: '/home/"{{ USER }}"/"{{ ansible_role_name }}"/files/join-command'
  delegate_to: localhost
