#SPDX-License-Identifier: MIT-0
---
# tasks file for k8s-master

##### Install Docker and its dependent components.

- name: Install packages that allow apt to be used over HTTPS
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add an apt signing key for Docker
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"    #{{ ansible_distribution_release }}
    state: present
    filename: docker

- name: Install docker and its dependecies
  ansible.builtin.apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
  notify:
    - docker status

- name: Configure containerd to use systemd cgroup driver ##
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^(\s*)SystemdCgroup\s*='
    line: '            SystemdCgroup = true'
    backrefs: yes
  notify: restart and enable containerd

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ USER }}"
    group: docker

### Disable swap.

- name: Create directory for Kubernetes apt keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Kubernetes apt signing key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: '0644'

- name: Add Kubernetes apt repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"

- name: Install Kubernetes binaries
  ansible.builtin.apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet 
      - kubeadm 
      - kubectl

- name: Set node IP fact
  ansible.builtin.set_fact:
    node_ip: "{{ ansible_default_ipv4.address }}"

- name: Configure node ip
  ansible.builtin.lineinfile:
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}
  notify:
    - restart kubelet

### Initialize the Kubernetes cluster. ###########################################################################################################################################################################################

- name: Load br_netfilter kernel module
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Ensure br_netfilter loads on boot
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      br_netfilter
    owner: root
    group: root
    mode: '0644'

- name: Configure Kubernetes networking sysctls
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/99-kubernetes.conf
    reload: true
  loop:
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { name: 'net.ipv4.ip_forward', value: '1' }

- name: Initialize the Kubernetes cluster using kubeadm
  ansible.builtin.command: kubeadm init --apiserver-advertise-address="192.168.50.10" --apiserver-cert-extra-sans="192.168.50.10" --node-name k8s-master --pod-network-cidr=192.168.0.0/16

### Setup the kube config file for user to access the Kubernetes cluster.

- name: Setup kubeconfig for user
  ansible.builtin.command: "{{ item }}"
  with_items:
    - mkdir -p /home/"{{ USER }}"/.kube
    - cp -i /etc/kubernetes/admin.conf /home/"{{ USER }}"/.kube/config
    - chown "{{ USER }}":"{{ USER }}" /home/"{{ USER }}"/.kube/config

### Setup the container networking provider and the network policy engine.

- name: Install calico pod network
  become: false
  ansible.builtin.command: kubectl create -f https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/calico.yaml

### Generate kube join command.

- name: Generate join command
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
