# all basic vars
# DOCKER VARS
DOCKER_KEYRING_PATH: /etc/apt/keyrings/
DOCKER_KEYRING_FILENAME: docker.asc

DOCKER_SIGNING_KEY: "https://download.docker.com/linux/ubuntu/gpg"
DOCKER_REPO_URL: "https://download.docker.com/linux/ubuntu"

# KUBERNETES VARS
KUBERNETES_VERSION: "v1.29"
KUBERNETES_SIGNING_KEY: "https://pkgs.k8s.io/core:/stable:/{{ KUBERNETES_VERSION }}/deb/Release.key"
KUBERNETES_KEYRING_PATH: /etc/apt/keyrings/
KUBERNETES_KEYRING_FILENAME: kubernetes-apt-keyring-{{ KUBERNETES_VERSION }}.asc
KUBECONFIG_PATH: /etc/kubernetes/admin.conf

CALICO_REPO: "https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico.yaml"

K8S_REPO_URL: "https://pkgs.k8s.io/core:/stable:/{{ KUBERNETES_VERSION }}/deb/"

# NETWORK VARS
K8S_API_ENDPOINT: k8s-api.internal

K8S_API_VIP: 10.10.10.100                                    # kube-vip vars
KUBE_VIP_VERSION: v1.2.4                                     # kube-vip vars
KUBE_VIP_INIT_KUBECONFIG: /etc/kubernetes/super-admin.conf   # kube-vip vars

METALLB_IP_RANGE: "10.10.10.200-10.10.10.210"    # metallb IPs pool
TRAEFIK_LB_IP: 10.10.10.200                      # traefik IP

TERRAFORM_APP_DOMAIN: temporary_example.com  #TO BE DEFINED

# CERT-MANAGER VARS
CERT_MANAGER_ACME_EMAIL: liora@example.com    #TO BE DEFINED
# STORAGE VARS
MINIO_NAMESPACE: "velero"
# MONITORING VARS
monitoring_namespace: "monitoring"
# CD VARS
argocd_namespace: "argocd"
